[build]
  command = "npm run build && node replace-env.js"
  publish = "dist/chat-gpt-clone/browser"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
